name: Chris Hooper
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7503
title: Xero User Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#45a1ee'
    - '#fbffff'
    - '#d4f2ff'
    - '#6eabdd'
    - '#bee0f2'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
